<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!-- Definición de la estructura del documento XML -->
    <!ELEMENT biblioteca (libros+)> <!-- Elemento 'biblioteca' que contiene uno o más elementos 'libros' -->
    <!ELEMENT libros (ISBN, autor, titulo, portada)> <!-- Elemento 'libros' que contiene elementos 'ISBN', 'autor', 'titulo' y 'portada' -->
    <!ELEMENT ISBN (#PCDATA)> <!-- Elemento 'ISBN' que contiene datos de caracteres (PCDATA) -->
    <!ELEMENT autor (#PCDATA)> <!-- Elemento 'autor' que contiene datos de caracteres (PCDATA) -->
    <!ELEMENT titulo (#PCDATA)> <!-- Elemento 'titulo' que contiene datos de caracteres (PCDATA) -->
    <!ELEMENT portada EMPTY> <!-- Elemento 'portada' que no puede contener nada -->
    
    <!ENTITY iesbilingue PUBLIC "https://iesventura.es//_ies_datos//bilingue_ok.jpg" "bilingue_ok.jpg" NDATA jpg>

    <!-- Definición de la NOTATION para el tipo de datos de 'portada' -->
    <!NOTATION jpg SYSTEM "image/jpg">
    
    <!-- Definición de atributos para el elemento 'portada' -->
    <!ATTLIST portada src ENTITY #REQUIRED> <!-- Atributo 'src' de 'portada' de tipo ENTITY y requerido -->
]>
<!-- Elemento raíz del documento XML -->
<biblioteca>
    <!-- Elementos 'libros' dentro de 'biblioteca' -->
    <libros>
        <!-- Elementos dentro de 'libros' -->
        <ISBN></ISBN>
        <autor></autor>
        <titulo></titulo>
        <!-- Elemento 'portada' con atributo 'src' -->
        <portada src="iesbilingue"/>
    </libros>
    <libros>
        <!-- Elementos dentro de 'libros' -->
        <ISBN></ISBN>
        <autor></autor>
        <titulo></titulo>
        <!-- Elemento 'portada' con atributo 'src' -->
        <portada src="iesbilingue"/>
    </libros>
    <libros>
        <!-- Elementos dentro de 'libros' -->
        <ISBN></ISBN>
        <autor></autor>
        <titulo></titulo>
        <!-- Elemento 'portada' con atributo 'src' -->
        <portada src="iesbilingue"/>
    </libros>
</biblioteca>
