<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programas [
    <!ELEMENT programas (programa+)>
    <!ELEMENT programa (#PCDATA)>
    <!-- El uso de "#IMPLIED" hace que sea opcional ñadir o no los atributos,
    si no se añaden no hay error y si se añaden deben llevar el tipo de
    datos indicados, "CDATA" es basicamente texto cualquiera. -->
    <!ATTLIST programa lenguaje CDATA #IMPLIED>
    <!ATTLIST programa annotation CDATA #IMPLIED>
]>
<programas>
    <programa lenguaje="Java"><!-- Código fuente 1. --></programa>
    <programa lenguaje="Java"><!-- Código fuente 2. --></programa>
    <programa lenguaje="CSharp"><!-- Código fuente 3. --></programa>
    <programa annotation="Hola"><!-- Código fuente 4. --></programa>
</programas>
