=== Agu1406/Portafolio/LenguajeDeMarcas/TerceraEvaluacion/UT4-XSD/24-05-16-RepasoPreExamenBingo/xsd/bingo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bingo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bolas" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="numeroBola" type="NumeroDeBola"/>
                    </xs:complexType>
                </xs:element>     
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="NumeroDeBola">
        <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="1"/>
            <xs:maxExclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Agu1406/Portafolio/Portafolio/DAW1/UT4-XSD/24-05-16-RepasoPreExamenBingo/bingo.xml
<?xml version="1.0" encoding="UTF-8"?>
<bingo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./xsd/bingo.xsd">
    <bolas numeroBola="2"></bolas>
    <bolas numeroBola="3"></bolas>
    <bolas numeroBola="4"></bolas>
    <bolas numeroBola="5"></bolas>
    <bolas numeroBola="6"></bolas>
    <bolas numeroBola="7"></bolas>
    <bolas numeroBola="8"></bolas>
    <bolas numeroBola="9"></bolas>
    <bolas numeroBola="10"></bolas>
    <bolas numeroBola="11"></bolas>
</bingo>
