<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE redSocial [
    <!-- Define el elemento raíz y su estructura de hijos que son elementos "persona" -->
    <!ELEMENT redSocial (persona+)>

    <!-- Define el elemento "persona" que incluye un elemento "nombre" y atributos "id" y "amigoID" -->
    <!ELEMENT persona (nombre)>
    <!ATTLIST persona 
        id ID #REQUIRED       <!-- ID único para cada persona -->
        amigoID IDREF #IMPLIED <!-- Referencia a otro ID de persona que indica un amigo -->
    >
    <!-- Define el elemento "nombre" que contiene texto -->
    <!ELEMENT nombre (#PCDATA)>
]>
<redSocial>
    <persona id="1" amigoID="p1">
        <nombre>Marta Lopez</nombre>
    </persona>
    <persona id="2" amigoID="p2">
        <nombre>Ismael Carvajal</nombre>
    </persona>
    <persona id="3" amigoID="p3">
        <nombre>David Polar</nombre>
    </persona>
    <persona id="4" amigoID="p4">
        <nombre>Agustin Marquez</nombre>
    </persona>
</redSocial>