<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
  <!-- Define el elemento raíz 'deportistas' que puede contener múltiples 'f1', y opcionalmente un 'tenis' y un 'roblox' -->
  <!ELEMENT deportistas (f1*, tenis?, roblox?)>
  
  <!-- Corrección: Define el elemento 'f1' para contener texto y especifica que puede tener un atributo 'pais' -->
  <!ELEMENT f1 (#PCDATA)>
  <!ATTLIST f1
    pais CDATA #FIXED "España"    <!-- Corrección: 'pais' ahora es un atributo fijo que siempre debe ser "España" -->
  >

  <!-- Define 'tenis' y 'roblox' como elementos que solo contienen texto -->
  <!ELEMENT tenis (#PCDATA)>
  <!ELEMENT roblox (#PCDATA)>
]>
<deportistas>
    <f1 pais="España">Carlos Sainz</f1>
    <f1>Fernando Alonso</f1>
    <tenis>Rafa nadal</tenis>
    <roblox>Agustin Marquez</roblox>
</deportistas>