=== Agu1406/Portafolio/backup_2024-12-10/Portafolio/DAW1/Lenguaje de Marcas/UT4-XSD/24-05-09-PrimerosEjerciciosXSD/XSDEjercicio1/BIBLIOTECA.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Define el elemento raíz del esquema -->
    <xs:element name="BIBLIOTECA">
        <!-- Define el tipo de contenido del elemento XSDBiblioteca -->
        <xs:complexType>
            <!-- Define la secuencia de elementos dentro de XSDBiblioteca -->
            <xs:sequence>
                <!-- Define el elemento LIBRO -->
                <xs:element name="LIBRO" minOccurs="1" maxOccurs="unbounded">
                    <!-- Define el tipo de contenido del elemento LIBRO -->
                    <xs:complexType>
                        <!-- Define la secuencia de elementos dentro de LIBRO -->
                        <xs:sequence>
                            <!-- Elemento TITULO: título del libro (obligatorio) -->
                            <xs:element name="TITULO" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <!-- Elemento AUTOR: autor(es) del libro (opcional, múltiples) -->
                            <xs:element name="AUTOR" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                            <!-- Elemento EDITORIAL: editorial del libro (obligatorio, único) -->
                            <xs:element name="EDITORIAL" type="xs:string" maxOccurs="1"/>
                            <!-- Elemento ANO: año de publicación del libro (opcional, múltiples) -->
                            <xs:element name="ANO" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <!-- Agregamos fuera del Sequence los atributos del libro. -->
                        <xs:attribute name="COD" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Agu1406/Portafolio/EvaluacionesTrimestres/TerceraEvaluacion/UT4-XSD/24-05-09-PrimerosEjerciciosXSD/Ejercicio1Biblioteca.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<BIBLIOTECA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDEjercicio1/BIBLIOTECA.xsd">
<!-- Declaración de la biblioteca -->
    <!-- Definición del primer libro -->
    <LIBRO COD="1">
        <!-- Título del primer libro -->
        <TITULO>XML para todos</TITULO>
        <!-- Autor del primer libro -->
        <AUTOR>Sergio Lujan Mora</AUTOR>
        <!-- Editorial del primer libro -->
        <EDITORIAL>UA Prensa</EDITORIAL>
    </LIBRO>
    <!-- Definición del segundo libro -->
    <LIBRO COD="11">
        <!-- Título del segundo libro -->
        <TITULO>Probar una opcion</TITULO>
        <!-- Autores del segundo libro -->
        <AUTOR>María Zayas Fonteles</AUTOR>
        <AUTOR>Sergio Luján Mora</AUTOR>
        <!-- Editorial del segundo libro -->
        <EDITORIAL>Prensa Editorial</EDITORIAL>
        <!-- Año de publicación del segundo libro -->
        <ANO>1994</ANO>
    </LIBRO>
</BIBLIOTECA>
